language: generic
sudo: required
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_3c6da100d0f9_key -iv $encrypted_3c6da100d0f9_iv
  -in polar-cargo-333117-8d85c0b7239f.json.enc -out polar-cargo-333117-8d85c0b7239f.json
  -d
- docker build -t chuqiyang/docker-react:latest -f Dockerfile.dev .
script:
- docker run -e CI=true chuqiyang/docker-react npm run build
deploy:
  provider: gae
  keyfile: polar-cargo-333117-8d85c0b7239f.json
  project: polar-cargo-333117